JakeChampion/fetch

fetch.js
These three constructor should expose to global (window and worker).
Especially Headers.
Because headers in fetch option accepts native object and Header object.
=> Expose Headers, Request and Response to window

README.md, fetch.js, test/server.js, test/test.js
https://fetch.spec.whatwg.org/#atomic-http-redirect-handling
Should behave just like XHR's redirection.
@annevk is `Response.prototype.url` supposed to be the redirected location? That was one of my feature wish list items that XHR can't do.
Closes #42.
/cc @dgraham @annevk
=> Test Atomic HTTP redirect handling

bower.json, fetch.js, package.json, test/.jshintrc, test/run.sh, test/test-worker.html, test/test.html, test/test.js, test/worker.js
I still :heart: QUnit because its super derpy and has no features, but I think Mocha is a little better suite for the things I'm hitting on our test suite.
* First class promise support
* Can run in web workers
* Supports skip/pending tests. Useful for marking tests has not supported in phantomjs or in certain browsers.
* The phantomjs runner works.
/cc @dgraham
=> Switch to Mocha

fetch.js, test/server.js, test/test.js
Incomplete.
I'm not sure how to support `credentials: 'omit'` with XHR.
Closes #43.
/cc @dgraham @annevk @mislav
=> Support credentials

fetch.js, test/test.js
This implementation is not case preserving when iterating over a Headers object.
See: https://fetch.spec.whatwg.org/#concept-header-name
=> Make Headers case insensitive though lowercasing.

fetch.js
ref: https://github.com/github/fetch/commit/74fa62be3dba24ea77f87d7aa5ab00ab90685b83
The above commit added a check for blob support to access the `response` property of the xhr. While that works for most cases, I'd argue the availability of XMLHTTPRequest2 and Blob are orthogonal and be treated as such.
For a practical use case, I haven't found a great solution for mocking XHR2 requests (generally use [Sinon.JS](https://github.com/cjohansen/Sinon.JS/issues/569)). Without the proposed change, any call to get a response body would return `undefined`. You can also imagine that any consumer who polyfills `Blob` in IE9 will run into the same type of issue.
Is there any harm in checking property existence in this instance?
=> Check for xhr.response only when supported.

fetch.js, test/test.js
Both Request and Response can accept a number of BodyInit types and are supposed to be consumable via a number of mixin readers.
@annevk seems like we're missing a way to consume `FormData` types. Theres no way to turn it into a Blob or ArrayBuffer. `new Response(formData).blob()` is going to become a clever hack if nothing official defined.
=> Improve Request/Response BodyInit consuming

README.md
I was reading through the README and spotted this.
=> Fix typo in npm install instructions

fetch.js
On some installs, both Firefox & Chrome throws:
```
"Fetch failed: " DOMException [InvalidAccessError]:
"A parameter or an operation is not supported by the underlying object"
```
Due to something like pre-set `async=false` (an overridden prototype, maybe?)
This fixes the above issue, and I don't see it introducing any problems.
=> Declare deliberate "async=true" on XMLHttpRequest open

fetch.js
This helps with isomorphic-fetch (currently it's relying on a fork that has these extra few lines:- https://github.com/matthew-andrews/fetch/blob/master/fetch.js#L3-5) and (I think) makes fetch's implementation simpler.
=> Centralise the checks for blob and form data support

fetch.js, test/test.js
[ https://github.com/whatwg/fetch/commit/e62f57b6c923f16e877ab56913a2a65388a7535a ]
Also wondering if also need to polyfill `ok` on the next version of Chrome where `fetch` might now be a partial implementation (sorry, google. my bad…)
---
Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1126483
=> Add a convenience `ok` getter on `Response`

fetch.js
Fixes https://github.com/github/fetch/issues/109.
It appears that cross-domain requests are not currently tested by the suite. However, the [test for this case](https://github.com/github/fetch/blob/89b449384fe7e1858615d2ecf85c78802815d7bb/test/test.js#L664) was not previously running since it was passing `credentials: 'include'`. With this change, the code actually runs, which was causing an exception in PhantomJS (see "Set xhr.withCredentials after xhr.open called.").
=> Fix credentials include

fetch.js, test/test.js
Changes the argument list passed into Headers#forEach to match the [iterable spec](http://heycam.github.io/webidl/#idl-iterable). Thanks for the link, @domenic.
Fixes #149.
=> Implement Headers#forEach correctly

.travis.yml
Docker-based infrastructure usually has faster build times due to virtually no queue waiting time.
=> Opt into new Travis infrastructure

README.md
* Added caveat about cookies
* Revamped HTTP error handling
* Simpler `request.url` workaround explanation
=> Improve documentation for `fetch` caveats

fetch.js, test/test.js
In sending undefined/null header values with the fetch polyfill, I was getting an error:
```javascript
TypeError: 'undefined' is not an object (evaluating 'value.toString')
at normalizeValue (fetch.js:20:21)
at Headers.append (fetch.js:42:14)
at Headers.<anonymous> (fetch.js:30:15)
at Array.forEach (native)
at new Headers (fetch.js:29:45)
at new Request (fetch.js:25:21)
at self.fetch (fetch.js:273:18)
```
I tested this against the native window.fetch implementation in Chrome 43.0.2357.81 and observed that primitive values were handled fine when set as request header values. Using string concatenation for string conversion - over `toString` (as noted in [Axel Rauschmeyer's article on the subject](http://www.2ality.com/2012/03/converting-to-string.html)) - brings parity between the two …
=> Properly convert undefined/null header values to strings.

fetch.js, test/test.js
I tried to match the spec as closely as possible. This should also make it possible to use `fetch(request, options)` invocation.
Fixes #177
/cc @dgraham @cesarandreu
=> Allow passing a Request instance to Request constructor

fetch.js
`this.url` is unconditionally assigned at the end of the constructor, so this assignment is unnecessary.
=> Remove superfluous assignment

test/test.js
`assert()` checks for a truthy first parameter, and uses the second as the error message.
=> Fix incorrect assertion

fetch.js, test/test.js
This solves part of what #132 does, but that PR seems abandoned.
https://fetch.spec.whatwg.org/#dom-global-fetch step 2 states that exceptions thrown by the Request constructor should cause fetch() to reject with the error. Exceptions thrown synchronously in the Promise callback will cause a rejection, so I've simply moved the Request ctor call into the Promise callback.
Manually verified that tests pass with native fetch implementations in Chrome and Firefox.
=> Reject the Promise returned by fetch() when Request ctor throws

fetch.js, test/test.js
This change adds support for the [Response.error()](https://fetch.spec.whatwg.org/#dom-response-error) and [Response.redirect()](https://fetch.spec.whatwg.org/#dom-response-redirect) static methods. Firefox and Chrome both support these methods.
=> Support Response.error() and Response.redirect()

test/test.js
This lets the `Response.redirect` test verify behavior of the method without being affected by the URL resolution issue (See #218), which is also an issue elsewhere.
=> Use absolute URL in Response.redirect test

fetch.js, test/test.js
This enables POSTing with an ArrayBuffer body, but doesn't change the existing support for receiving ArrayBuffer responses (via blob)
=> Allow making a POST request with an ArrayBuffer body

fetch.js, test/test.js
Summary: The process of extracting a body from a passed in body object
(described here: https://fetch.spec.whatwg.org/#concept-bodyinit-extract)
creates both a byte stream and a corresponding `Content-Type` value. These two
values are used in the constructor of `Request` and `Response` objects to
initialize the body and to set an initial `Content-Type` header.
This change makes `Body._initBody()` return the `Content-Type` value
corresponding to the type of the object passed in, and to set that header in
the corresponding `Request` and `Response` objects that are being constructed.
There's a little bit of a dance I need to do in Request to keep track of where
the body is coming from, because we're only supposed to be setting the
`Content-Type` header if we're getting the body from the …
=> Make fetch add a `Content-Type` header based on the type of the body.

fetch.js
As per: https://github.com/github/fetch/issues/125#issuecomment-169118755
Resolves #252, #238, #165, #125, #124, and probably a few others.
There are a lot of different ways this code could be written. If you have style preferences contrary to the way I've done this, I'd be very happy to change it.
=> Handle cases where `self` isn't defined

examples/index.html
fixes example to use api.github.com rather than github.com
=> fix example

fetch.js, test/test.js
Adds `entries`, `keys`, and `values` iterator functions to `Headers`. Each iterator, and `Headers` itself, is also `iterable` if the browser supports `Symbol.iterator`. The [medikoo/es6-symbol](https://github.com/medikoo/es6-symbol) polyfill may be used in browsers without `Symbol`.
Background:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#iterable
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators
- https://fetch.spec.whatwg.org/#headers
- http://heycam.github.io/webidl/#idl-iterable
- http://heycam.github.io/webidl/#es-iterable
Closes #292.
/cc @lukeapage @dkfiresky
=> Add Headers iterators

.jshintrc, fetch.js, package.json, test/test-worker.html, test/test.html, test/test.js
Allows a [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) object to be serialized as a request body with a `Content-Type: application/x-www-form-urlencoded`  header.
```js
var params = new URLSearchParams()
params.append('user', 'hubot')
fetch('/test', {method: 'post', body: params})
```
Related:
- https://fetch.spec.whatwg.org/#body-mixin
- https://url.spec.whatwg.org/#urlsearchparams
- https://developers.google.com/web/updates/2016/01/urlsearchparams
- https://github.com/WebReflection/url-search-params
Closes #296.
/cc @mislav @btd
=> Add support for URLSearchParams POST body

fetch.js
From https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#getAllResponseHeaders():
> Returns all the response headers, separated by CRLF, as a string, or null if no response has been received.
I discovered this on Android, once when `xhr.getAllResponseHeaders()` evaluated to `null`.
=> Guard against `xhr.getAllResponseHeaders()` being `null`

README.md
HTTP methods are case-sensitive. The examples in the README currently
lead developers to think that this API normalizes all of the method
names to uppercase, leading to issues like #37 and #254.
Setting the right precedent in the README will prevent developers
from making mistake of trying to use method: 'patch' (or any
other verb that isn't normalized for backwards compatibility).
=> Use uppercase methods in README

fetch.js
Firefox and Chrome trigger the request's `onerror` handler when a timeout occurs. Safari triggers the `ontimeout` handler.
This can be observed by making a request to an unroutable address:
```js
var xhr = new XMLHttpRequest()
xhr.onload = console.log.bind(console, 'loaded')
xhr.onerror = console.log.bind(console, 'errored')
xhr.ontimeout = console.log.bind(console, 'timeout')
xhr.open('GET', 'http://10.255.255.1')
xhr.send()
```
Fixes #294.
@mislav @fabioberger
=> Reject promise on request timeout

package.json, script/phantomjs, test/mocha-phantomjs-hooks.js, test/test-worker.html, test/test.html
This switches to the more lightweight mocha-phantomjs-core project that allows us to use system PhantomJS, which should be the later 2.x series rather than 1.9.
/cc @dgraham
=> Switch to `mocha-phantomjs-core` and system PhantomJS

README.md
I had the same question as @abimelex in #275, and figured it would be useful to have a short example in the README.
=> Add ES2015+ example

README.md
The currently linked solution for Webpack usage is incorrect as it does not define `fetch` as a global and as a result will fail when an application uses external modules which expect `fetch` to be available, as those will generally not be processed by Webpack's `ProvidePlugin`.
Including `fetch` in the `entry` configuration of Webpack is the correct way to polyfill and fixes this issue. This is consistent with how other polyfills are used e.g. [babel-polyfill](https://babeljs.io/docs/usage/polyfill/), and does not require any special loader.
=> Update Webpack section in README

Makefile, script/saucelabs, script/saucelabs-api
- Update sauce_connect
- Timeout handling for sauce_connect
- Have `saucelabs-api` show error message on HTTP errors
- Have `saucelabs-api` exit with nonzero on errors
- Exit with nonzero if Saucelabs reports that 0 tests have ran
- Abort Saucelabs API polling on "test error" (unsure what causes this)
This will hopefully give us more insight into Saucelabs failures during CI runs.
=> Better error handling with Saucelabs

fetch.js
HTTP headers are case-insensitive
=> make X-Request-URL header case-insensitive

fetch.js, package.json, test/test.js
Various loosely related fixes, most important being the ability to re-use the same GET Request instance for multiple `fetch()` invocations.
The huge diff in tests is due to tests reorg.
/cc @josh @dgraham
=> Spec compatibility for Request/Response constructors and cloning

Makefile, fetch.js, script/phantomjs, test/test.js
Problem: passing ArrayBuffer directly to XHR is considered deprecated and Safari and PhantomJS will throw warnings about it. Instead, an ArrayBuffer should be wrapped in an ArrayBufferView instance. However, the polyfill used to reject those instances as unrecognized body types, and our users were not able to work around the deprecation warning. This adds support for those types and brings us closer to spec compatibility.
Supporting IE 10 & 11 complicates matters here, because `ArrayBuffer.isView` polyfill is needed for IE 10, and a special case for DataView objects is necessary for IE 10-11.
Fixes #344, fixes #343, references #351
/cc @dgraham
=> Support ArrayBufferView types as POST body

fetch.js, test/test.js
Consider this Headers object:
```js
var h = new Headers()
h.append('accept', 'text/html')
h.append('accept', 'text/plain')
h.append('content-type', 'application/json')
```
Before:
- `h.get('accept')` returned `text/html`
- `h.getAll('accept')` returned an array of values
- `h.forEach` (and other iterables) did distinct iterations for each value of the same header
Now:
- `h.get('accept')` returns `text/html,text/plain`
- `h.getAll()` is no more
- `h.forEach` (and other iterables) now only do one iteration for each headers name, regardless of multiple values
This is in accordance with Section 3.1.2 of the spec, "combine" concept. https://github.com/whatwg/fetch/commit/42464c8c3d2fd3437a19fc6afd2438a0fd42dde8
The updated tests currently break in Chrome and Firefox when exercising the native …
=> Change Headers multiple value handling for spec compatibility

fetch.js
The change to fix this issue https://github.com/github/fetch/issues/422 has created another issue for our app on devices running iOS 8.2 and iOS 9. The impact prevents these users from using our app entirely.
More specifically, the result of splitting by `\r\n` and not both `\r\n` and `\n` is a malformed response header with all the actual headers put into the 'pragma' key and a content type of `text/plain;charset=UTF-8` instead of `application/json`.
Source:
http://stackoverflow.com/a/5757349
more specifically, https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.3
=> Support Tolerance Provision when parsing headers

fetch.js, test/test.js
This aims to match the behavior that the IDL of the spec defines.
Fixes https://github.com/github/fetch/issues/462
/cc @dgraham
=> Treat any non-Request arg to `new Request()` as string url

README.md
Improve various aspects of the language in the README, some being typos.
=> Improve README language

fetch.js, test/test.js
[From the spec](https://fetch.spec.whatwg.org/#typedefdef-headersinit), it looks like the `Headers` constructor should accept an array of arrays.
I've adapted [the example](https://fetch.spec.whatwg.org/#example-headers-class) for the tests:
```js
var meta = { "Content-Type": "text/xml", "Breaking-Bad": "<3" }
new Headers(meta)
// The above is equivalent to
var meta = [
[ "Content-Type", "text/xml" ],
[ "Breaking-Bad", "<3" ]
]
new Headers(meta)
```
This came up for me as an issue using `stream-http` in Edge with the Financial Times polyfill.  I've opened jhiesey/stream-http#71 and Financial-Times/polyfill-service#1091 in case this can be addressed elsewhere, but it looks to me like this might be the right fix.
=> Accept array in Headers constructor

fetch.js
For issue https://github.com/github/fetch/issues/489
=> Support obs-fold as header delimiter

README.md
Safari 10.1 now natively supports fetch. https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html
=> Added safari to native fetch browser support.

fetch.js
@mislav @mpfluger
Added global replace as @pseidemann mentioned.
https://github.com/github/fetch/pull/491#issuecomment-284801588
Not sure how you would want to expose `parseHeaders` for testing but here are some suggestions for tests:
```
suite('parseHeaders', function() {
test('parses raw headers with line feed'), function() {
var rawHeaders = 'Tolerance-Provision-Value-1: key1\nTolerance-Provision-Value-2: key2\nTolerance-Provision-Value-3: key3'
var headers = parseHeaders(rawHeaders);
assert.equal(headers.get('Tolerance-Provision-Value-1'),'key1')
assert.equal(headers.get('Tolerance-Provision-Value-2'),'key2')
assert.equal(headers.get('Tolerance-Provision-Value-3'),'key3')
})
test('parses raw headers with carriage return line feed'), function() {
var rawHeaders = 'Basic-Rules-Value-1: …
```
=> Add global replace for processing raw headers

fetch.js
If the default value of `withCredentials` is `true`, as opposed to `false`, the library will send the cookies even if `credentials: omit` is specified. This affects React Native where the default value is `true` since cross-origin concerns don't apply.
=> Ensure cookies aren't sent if `credentials: omit`

fetch.js, test/test.js
This allows the Response constructor to accept a status code that's
explicitly set to undefined. Native fetch implementations in Chrome and
Firefox behave this way.
The following now works, but would previously throw an error:
new Response('', { status: undefined })
=> Allow undefined Response status

index.html
Because of the spec of XMLHttpRequest, `fetch` polyfill can't prevent sending and receiving same-origin cookies when `credentials: 'omit'`.
This behavior is very confusing when app supports both modern and legacy browsers.
I think this should be clearly documented as a caveat.
=> Add caveat about disabling same-origin cookies

README.md
I found the bullet on node.js particularly confusing. This breaks the parallel structure, but I think it's worth it. Made a few more edits while I was at it.
=> Tweak the wording of the “Read this first” section

README.md, fetch.js, test/test.js
Spec changed in April: https://github.com/whatwg/fetch/pull/585
Latest Firefox and Chrome implement the new default.
=> Change `credentials` default value to `same-origin`

CODE_OF_CONDUCT.md, README.md
The Open Code of Conduct has been defunct for a while.
Should we link to it from the README or any documentation or this discoverable enough by itself?
Fixes #648
=> Adopt Contributor Covenant Code of Conduct

fetch.js, test/test.js
The polyfill used to throw an exception, but the spec dictates that unsupported body types are simply converted to string.
Closes #576, closes #642
=> Match spec behavior re: unsupported body type

Makefile, fetch.js.flow, package.json
We can't really use Headers, Request, and Response classes that Flow already has built in because:
- This polyfill won't work if a native Request instance is passed to polyfill `fetch()`;
- Not all properties in the Fetch Standard are supported in the polyfill.
Therefore, the class definitions are replicated and edited for compatibility.
=> Add flow definitions

README.md
People are getting tripped up on these being unavailable in the polyfill.
https://github.com/github/fetch/pull/285#issuecomment-548531771
=> Document more common pitfalls in the README

fetch.js, test/test.js
According to [WHATWG fetch specification](https://fetch.spec.whatwg.org/#response-class) default statusText for Response should be "" (empty string).
Fixes #696
=> Change default statusText for Response

fetch.js
Fixes wheresrhys/fetch-mock#415
Details: fetch-mock wraps the Response object in an ES6 Proxy to
provide useful test harness features such as flush.  However, on
ES5 browsers without fetch or Proxy support pollyfills must be used;
the proxy-pollyfill is unable to proxy an attribute unless it exists
on the object before the Proxy is created.  This change ensures
Response.bodyUsed exists on the instance, while maintaining the
semantic of setting Request.bodyUsed in the constructor before
_initBody is called.
=> Compatibility for fetch-mock using proxy-pollyfill

fetch.js
In the [section 3.2.6 of the HTTP RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2.6), it denotes the following about HTTP headers:
>  Most HTTP header field values are defined using common syntax
components (token, quoted-string, and comment) separated by
whitespace or specific delimiting characters.  Delimiters are chosen
from the set of US-ASCII visual characters not allowed in a token
(DQUOTE and "(),/:;<=>?@[\]{}").
>
>     token          = 1*tchar
>
>     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
>                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
>                    / DIGIT / ALPHA
>                    ; any VCHAR, except delimiters
Note the `tchar` definition allows use of an exclamation mark, but the validator for `normalizeName` does not …
=> Allow exclamation mark as valid header character

fetch.js, rollup.config.js
Fixes https://github.com/github/fetch/issues/657
=> Fix https://github.com/github/fetch/issues/657

fetch.js
Fixes https://github.com/github/fetch/issues/629
=> Add support for no-cache and no-store via a cache-busting querystring parameter

fetch.js
fixes https://github.com/github/fetch/issues/724
=> Detect if DOMException exists via typeof instead of trying to call it and catching the exception which may get thrown

fetch.js
Reverts github/fetch#797
Some browser have `DOMException` but do not allow it to be constructed via `new`
Fixes https://github.com/github/fetch/issues/799
=> Revert "Detect if DOMException exists via typeof instead of trying to call it and catching the exception which may get thrown"

README.md
Fixes https://github.com/github/fetch/issues/800
=> Recommend an AbortController polyfill which is fully synchronous

fetch.js, rollup.config.js
fixes https://github.com/github/fetch/issues/802
=> Stop using top-level `this` to stop rollup warning

fetch.js
Fixes https://github.com/github/fetch/issues/801
=> Make Response.arrayBuffer() always resolve with a `ArrayBuffer`

fetch.js
Fixes #748 - as discussed in the ticket, this change avoids the use of split via regex, swapping it out for less efficient, but functional ES5 code
//cc @JakeChampion
=> Work-around for core-js issue parsing headers

fetch.js
If an invalid name for a header is provided, the library throws an error. This is correct, but in certain scenarios it can be hard to understand which header name actually causes the error.
This PR appends the name of such error to the error message
=> add header name in case of error

fetch.js, test/test.js
Inside Response constructor, this line:
`this.statusText = 'statusText' in options ? options.statusText : ''` is incorrect and should be:
`this.statusText = options.statusText === undefined ? '' : '' + options.statusText`
- new Response('').statusText ==> ""
- new Response('', {statusText: undefined}).statusText ==> ""
- new Response('', {statusText: null}).statusText ==> "null" (yes a string)
- new Response('', {statusText: ''}).statusText ==> ""
- new Response('', {statusText: 'hello'}).statusText ==> "hello"
- new Response('', {statusText: 0}).statusText ==> '0'
- new Response('', {statusText: 1}).statusText ==> '1'
<details><summary>Screenshots</summary>
<p>
</p>
</details>
- new Response('').statusText ==> "" ==> OK
- new Response('', {statusText: undefined}).statusText ==> undefined …
=> Fix Response.statusText

fetch.js
Ensures `request._bodyInit` (the internal representation of a request body) is always set to a `[object Object]` string representation of a body in case it has a non-stringified JSON body and the `Content-Type` header stating an expected JSON body.
- See #856
=> Represent non-stringified JSON request body as an [object Object] string

.eslintignore, .eslintrc.json, package.json, test/test.js
Fix for this report:
```
2021-02-17T16:13:57.668Z
Found: eslint@4.19.1
node_modules/eslint
dev eslint@"^4.19.1" from the root project
peer eslint@">=4.19.1" from eslint-plugin-eslint-comments@3.2.0
node_modules/eslint-plugin-eslint-comments
eslint-plugin-eslint-comments@">=3.0.1" from eslint-plugin-github@1.10.0
node_modules/eslint-plugin-github
dev eslint-plugin-github@"^1.6.0" from the root project
peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0" from eslint-plugin-import@2.22.1
node_modules/eslint-plugin-import
eslint-plugin-import@">=2.11.0" from eslint-plugin-github@1.10.0
node_modules/eslint-plugin-github
dev eslint-plugin-github@"^1.6.0" from the root project
peer eslint@">=4.19.0" from eslint-plugin-github@1.10.0
node_modules/eslint-plugin-github
dev …
```
=> Fix eslint and eslint-plugin-github dependency conflicts

fetch.js, package.json
Version 3.6.0 (https://github.com/github/fetch/pull/881/files#diff-3fc6f1265a180d15035618e36ca1da88d092bacb4fc10a423938fa62e4f5f58fR259) broke MSIE compatibility.
`String.prototype.includes` is not available within any version of MSIE – [see compatibility table on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#browser_compatibility)
=> Fix MSIE compatibility

fetch.js, test/test.js
https://fetch.spec.whatwg.org/#request-class
new Request(input, init) constructor step : 28
> Set this’s signal to a new AbortSignal object with this’s relevant Realm.
latest Chrome :
```js
new Request('').signal
// AbortSignal {aborted: false, onabort: null}
```
Also checked Safari/Firefox and this is implemented in all of them.
-------
I wasn't sure how to run the test suite.
I had een error that seemed unrelated to the actual feature tests :
```
25 07 2021 09:11:12.524:INFO [framework.detect-browsers]: The following browsers will be used: [ 'ChromeHeadlessNoSandbox',
'ChromeCanaryHeadlessNoSandbox',
'FirefoxHeadless',
'Safari',
'SafariTechPreview' ]
25 07 2021 09:11:12.605:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9877/
25 07 2021 09:11:12.605:INFO [launcher]: …
```
=> always set a signal on Request

README.md
Checked the link, skipping the redirect HTTP => HTTPS and to the new pattern this way 0:-)
=> Update caniuse link to use HTTPS and new pattern

fetch.js
Recently I found that the polyfill for `fetch()` has not normalized the `patch` method as uppercase, and it seems like a bug like native implementation. Should we add some request methods to solve this problem?
REF: https://github.com/nodejs/help/issues/2184
=> Add some missed methods which should be normalized as uppercase

fetch.js, test/server.js, test/test.js
@JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.
I also can't just test `parseHeaders()` since its private and not globally exported (rightfully so).
So do you have any idea how to test my fix properly?
Fixes #930
=> fix: ignore not throw on invalid response headers

.github/workflows/lock.yml, .github/workflows/node.js.yml
Closes #1272 
- lock.yml: only needs issue and pull request write permission according to https://github.com/dessant/lock-threads#examples
- ci.yml: I wasn't able to test it sice it is breaking due to some lint error. Anyway, the workflow does not seem to need more than contents read permission.
=> Set minimal permissions to github workflows

fetch.js, test/test.js
#1371 
As noted in 1371, and other discussion outside of whatwg/fetch, it's been found that adding the RangeError for statuses outside of 200-599 causes local File fetches to fail.
i.e.
fetch("file://some/local/path")
This PR adds a simple check for the file path before returning the response, it could alternatively be added to the 200/500 check as a not condition.
Not sure if this has the potential to break other things, or if there's a better way to handle the RangeError issue with `file://` not setting a status.
Test: In it's current state, I'm unsure how to test this, as most browsers block the use of `file://` and any systems that allow may return a status, and may not.
Thanks
=> Fix - File fetching broken since commit 0c1d2b9

fetch.js
Both `xhr.onerror` and `xhr.ontimeout` throw the same error.
I think it would be beneficial to have both handler emit errors with a different message. This way, applications can behave differently based on the error message. Especially since there is no such thing as a unique error code do distinguish both errors.
=> fix: Have unique error messages for xhr timeouts and errors

.github/workflows/node.js.yml, .github/workflows/scorecard.yml
Hi, just a minor fix to the workflows to run on push at main, they were still looking for pushes on "master".
=> Fix workflows to run on main instead of master

fetch.js
PR will resolve https://github.com/JakeChampion/fetch/issues/1403
Since startsWith has a similar level of support as fetch, we have replaced it with indexOf to ensure that the module does not require additional polyfills.
=> Replaced startsWith with indexOf to Avoid Additional Polyfill Dependencies

fetch.js, test/test.js
- Fixes error caused in https://github.com/JakeChampion/fetch/commit/0c1d2b97b7edf636323534b13626a8bb9f5fe22d, by which `Response.error().ok === true` where it should be `false` because `Response.error().status < 200`.
- Adds test assertion
`Response.error` internally constructs a valid Response and overwrites properties as necessary.
Now that `Response` must be constructed with a valid status, the constructed Response will be `ok`, so this property needs to be overwritten as well.
=> Fix: Response.error().ok === false
