- test/.jshintrc
- test/test.html
- test/test.js
Adds promise test helper until Qunit supports promise's officially.
Gets some nicer error messages when stuff throws instead of timing out.
/cc @dgraham
> Add promise test helper

- fetch.js
- test/server.js
- test/test.js
Perhaps it should request with `xhr.responseType = 'arraybuffer'` and convert to a string manually in `text()`.
> Support fetching binary data using xhr.responseType = 'blob'

- test/server.js
- test/test.js
HTTP Network or cache fetch step 13 gates on the credentials flag.
> Fetch spec requires non-omit credentials mode to set cookies too.

- test/test.js
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27846
> HEAD/GET Request should throw if body is passed

- package.json
This would be nice as this information is displayed in the npm repository.
> Add metadata for repository, bugs and license

- fetch.js
Not really sure if I'm doing this right but this felt like it was missing.
> If cors, with credentials

- README.md
as suggested in https://github.com/github/fetch/issues/9
> node.js module link

- .npmignore
- package.json
(#80)
Create .npmignore
`test/`
`examples/`
`.npmignore`
`.gitignore`
`.jshintrc`
`.travis.yml`
> adds .npmignore

- fetch.js
- test/test.js
> Headers constructor in Response constructor

- fetch.js
resolves https://github.com/github/fetch/issues/135
> only define _initBody once

- README.md
Closes #193. Thanks for documenting this, @matiassingers.
> Add webpack usage link.

- .travis.yml
- README.md
- fetch.js
> Drop IE-specific status codes workarounds and require IE10+

- fetch.js
remove duplicate code in values, keys, entries method for Header
> refactor Header iterator methods

- index.html
> Fix "respose" typo

- fetch.js
- test/test.js
> Support ArrayBuffer in BodyInit

- README.md
It seems simple and useful to users that already use Yarn. I know that most users don't know about Yarn yet. So I put another option.
> Added yarn command as option to installation

- index.html
https://github.com/github/fetch/pull/640
> Change `credentials` default to "same-origin"

- fetch.js
Fixes https://github.com/github/fetch/issues/737
> If headers are passed in via a Record then do not normalise the header names as part of the request

- README.md
https://github.com/github/fetch/issues/787
> Call out #Caveats higher up in readme

- .eslintrc.json
- fetch.js
> Use globalThis as the global object if it exists

- fetch.js
This reverts commit 5c6b055e6ae6f718f416c94bfcdc89693d0abdcb.
Fixes https://github.com/github/fetch/issues/923 https://github.com/github/fetch/issues/922 https://github.com/github/fetch/issues/918
> Revert "Represent non-stringified JSON request body as an [object Object] string"

- fetch.js
fixes https://github.com/JakeChampion/fetch/issues/1026
> dont shadow `global`

- fetch.js
- test/test.js
fixes https://github.com/JakeChampion/fetch/issues/1213
> validate status is in range

- fetch.js
- test/test.js
fixes https://github.com/JakeChampion/fetch/issues/1214
>  fix: when no body supplied, do not set bodyUsed to true 

- fetch.js
solves https://github.com/JakeChampion/fetch/issues/860
> use globals if they exist

- fetch.js
resolves https://github.com/JakeChampion/fetch/issues/992
> Define Body.arrayBuffer even if support.blob is false 

- fetch.js
- test/test.js
fixes https://github.com/JakeChampion/fetch/issues/1235
> fix: Headers only accepts array which have nested array of length 2

- fetch.js
fixes https://github.com/JakeChampion/fetch/issues/1059
> respect charset within readBlobAsText

- fetch.js
Reverts JakeChampion/fetch#1364
need to figure out a better solution as this causes an issue for many consumers 
fixes https://github.com/JakeChampion/fetch/issues/1365
> Revert "Resolves https://github.com/JakeChampion/fetch/issues/928"

- .github/dependabot.yml
- .github/workflows/lock.yml
- .github/workflows/node.js.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
Closes #1386 
Hash pinned actions used on workflows and enabled the dependabot to group PRs and max of 1 for week.
> Hash pin actions used on workflows and enable dependabot
